"""Build the anonymized IEMCON submission from the course version, then prove it.

The manual version of this went wrong twice: the author-block match is sensitive to
line endings (git's autocrlf flips them on checkout), and when the match silently
failed the compile still ran and produced a PDF with the real names in it. So this
script matches on normalized text, and refuses to leave a PDF behind unless
pdftotext confirms the rendered output is clean.

Run: python scripts/make-iemcon-anon.py        (from the repo root)
"""

import re
import shutil
import subprocess
import sys
from pathlib import Path

PAPER = Path("docs/paper")
SRC = PAPER / "capstone_week13_full.tex"
DST = PAPER / "iemcon2026.tex"
PDF = PAPER / "iemcon2026.pdf"

# Anything that would break double-blind if it reached the rendered PDF.
IDENTITY = ["En-Ping", "Tong Wu", "Shiting", "Mengshan", "Northeastern", "Khoury",
            "Indigenomics", "Coria", "Coady", "Vancouver"]

ANON_AUTHOR = r"\author{\IEEEauthorblockN{Authors omitted for double-blind review}}"
HEADER = """% IEEE IEMCON 2026 - DOUBLE-BLIND SUBMISSION. Generated by
% scripts/make-iemcon-anon.py from capstone_week13_full.tex: identical text,
% anonymous author block. Do NOT commit while under review.
% CS7980 Capstone paper"""


def fail(msg: str) -> None:
    print(f"FAILED: {msg}", file=sys.stderr)
    # Never leave a stale or non-anonymous artifact around to be uploaded by mistake.
    PDF.unlink(missing_ok=True)
    sys.exit(1)


text = SRC.read_text(encoding="utf-8").replace("\r\n", "\n")

# The author block spans several lines and its whitespace has moved before; match the
# whole \author{...} group by its opening rather than by an exact literal.
new_text, n = re.subn(
    r"\\author\{\\IEEEauthorblockN\{En-Ping.*?Canada\}\}",
    ANON_AUTHOR.replace("\\", "\\\\"),
    text,
    count=1,
    flags=re.DOTALL,
)
if n != 1:
    fail("author block not found — the course version's \\author{...} block changed shape")
text = new_text

if "% CS7980 Capstone paper" not in text:
    fail("header anchor '% CS7980 Capstone paper' not found")
text = text.replace("% CS7980 Capstone paper", HEADER, 1)

leaks = [s for s in IDENTITY if s in text]
if leaks:
    fail(f"identity strings still in the .tex: {leaks}")

DST.write_text(text, encoding="utf-8", newline="\n")
print(f"wrote {DST}")

for _ in range(2):  # twice, so \ref and \cite resolve
    subprocess.run(["pdflatex", "-interaction=nonstopmode", DST.name],
                   cwd=PAPER, check=False, stdout=subprocess.DEVNULL)
if not PDF.exists():
    fail("pdflatex produced no PDF")

# The check that actually matters: what does the rendered page say?
try:
    rendered = subprocess.run(["pdftotext", PDF.name, "-"], cwd=PAPER,
                              capture_output=True, text=True, check=True).stdout
except (OSError, subprocess.CalledProcessError):
    fail("pdftotext unavailable — cannot verify the rendered PDF, refusing to vouch for it")

rendered_leaks = [s for s in IDENTITY if s.lower() in rendered.lower()]
if rendered_leaks:
    fail(f"identity strings in the RENDERED PDF: {rendered_leaks}")
if "omitted for double-blind review" not in rendered:
    fail("anonymous author line missing from the rendered PDF")

pages = rendered.count("\f")
print(f"verified: {pages} pages, no identity strings, anonymous author line present")
